"""add portfolio history table

Revision ID: f7ae2fb1bdca
Revises: 6e76f4d40d3c
Create Date: 2026-01-02 13:57:01.510776

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f7ae2fb1bdca"
down_revision: str | Sequence[str] | None = "6e76f4d40d3c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "portfolio_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("total_value", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("total_pnl_percentage", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("portfolio_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["portfolio_id"], ["portfolios.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("portfolio_id", "date", name="uq_portfolio_history_date"),
    )
    op.create_index(op.f("ix_portfolio_history_date"), "portfolio_history", ["date"], unique=False)
    op.create_index(op.f("ix_portfolio_history_id"), "portfolio_history", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_portfolio_history_id"), table_name="portfolio_history")
    op.drop_index(op.f("ix_portfolio_history_date"), table_name="portfolio_history")
    op.drop_table("portfolio_history")
    # ### end Alembic commands ###
